# Generated by Django 5.0 on 2024-02-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_product_available_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogry',
            new_name='categry',
        ),
    ]
